export default [
  "strapi::logger",
  "strapi::errors",
  "strapi::security",
  {
    name: "strapi::cors",
    config: {
      origin: [
        "https://lzastava.com",
        "http://lzastava.com",
        "https://www.lzastava.com",
        "http://www.lzastava.com",
        "https://camp.lzastava.com",
        "http://camp.lzastava.com",
        "http://centre.lzastava.com",
        "https://centre.lzastava.com",
        "http://otdyh.lzastava.com",
        "https://otdyh.lzastava.com",
        "https://www.camp.lzastava.com",
        "http://www.camp.lzastava.com",
        "http://www.centre.lzastava.com",
        "https://www.centre.lzastava.com",
        "http://www.otdyh.lzastava.com",
        "https://www.otdyh.lzastava.com",
        "http://test.lzastava.com",
        "https://test.lzastava.com",
        "http://test.lzastava.com",
        // "http://localhost:5174",
        // "http://192.168.0.104:5174",
      ],
      methods: ["GET", "POST", "PUT", "DELETE", "PATCH"],
      headers: "*",
    },
  },
  "strapi::poweredBy",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
